// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ResumeGeneratorTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void resumeGenerator() {
        driver.get("http://resumegenerator.rf.gd/ResumeGenerator.html");
        driver.manage().window().setSize(new Dimension(1536, 824));
        driver.findElement(By.id("nameField")).click();
        driver.findElement(By.id("nameField")).sendKeys("Shivansh Rai");
        driver.findElement(By.id("contactField")).click();
        driver.findElement(By.id("contactField")).sendKeys("123456789");
        driver.findElement(By.id("addressField")).click();
        driver.findElement(By.id("addressField")).sendKeys("Address");
        driver.findElement(By.id("fbField")).click();
        driver.findElement(By.id("fbField")).sendKeys("https://facebook.com");
        driver.findElement(By.id("instaField")).click();
        driver.findElement(By.id("instaField")).sendKeys("https://instagram.com");
        driver.findElement(By.id("LinkedInField")).click();
        driver.findElement(By.id("LinkedInField")).sendKeys("https://linkedin.com");
        driver.findElement(By.id("objectiveField")).click();
        driver.findElement(By.id("objectiveField")).sendKeys("Objective ");
        driver.findElement(By.cssSelector(".weField")).click();
        driver.findElement(By.cssSelector(".weField")).sendKeys("Work Experience 1");
        driver.findElement(By.cssSelector("#weAddButton > .btn")).click();
        driver.findElement(By.cssSelector(".form-control:nth-child(3)")).click();
        driver.findElement(By.cssSelector(".form-control:nth-child(3)")).sendKeys("Work Experience 2");
        driver.findElement(By.cssSelector("#weAddButton > .btn")).click();
        driver.findElement(By.cssSelector(".form-control:nth-child(4)")).click();
        driver.findElement(By.cssSelector(".form-control:nth-child(4)")).sendKeys("Work Experience 3");
        driver.findElement(By.cssSelector(".eqField")).click();
        driver.findElement(By.cssSelector(".eqField")).sendKeys("Academic Qualification 1");
        driver.findElement(By.cssSelector("#aqAddButton > .btn")).click();
        driver.findElement(By.cssSelector(".eqField:nth-child(3)")).click();
        driver.findElement(By.cssSelector(".eqField:nth-child(3)")).sendKeys("Academic Qualification 2");
        driver.findElement(By.cssSelector(".btn-lg")).click();
        driver.findElement(By.cssSelector(".container > .background")).click();
    }
}
